export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';

export const FETCH_DONUTS = 'FETCH_DONUTS';
export const FETCH_DONUTS_SUCCESS = 'FETCH_DONUTS_SUCCESS';
export const FETCH_DONUTS_FAILURE = 'FETCH_DONUTS_FAILURE';

export const FETCH_BARS = 'FETCH_BARS';
export const FETCH_BARS_SUCCESS = 'FETCH_BARS_SUCCESS';
export const FETCH_BARS_FAILURE = 'FETCH_BARS_FAILURE';

export const FETCH_LINES = 'FETCH_LINES';
export const FETCH_LINES_SUCCESS = 'FETCH_LINES_SUCCESS';
export const FETCH_LINES_FAILURE = 'FETCH_LINES_FAILURE';

